### ISSUE TITLE
Scrollable ProgressBartime on our playlist

### ISSUE THREAD

**Issue by Yehezkiel01** [nus-angklung/gili#42]

**Comment by RussellDash332** [comment]
@Yehezkiel01 the current progress is like in the video. The problem is that the progress bar slider does not move automatically along with the song unless manually dragged.

I tried to interchange on:change and on:input for both volume slider and progress slider because one change can interrupt the other. I guess doing on:change on the volume slider won't affect the real volume but will affect the song as shown in the video.

Let me know what you think 😄 🆘

https://user-images.githubusercontent.com/63991775/105688433-8dfc6a80-5f34-11eb-8f56-36c634e75b25.mp4

Refer to https://svelte.dev/repl/5cf670ec8d434d7098723fe057dda04a?version=3.28.0

**Comment by RussellDash332** [comment]
Update on the progress :
Total revamp on the sliders, managed to use the one I mentioned in #43. Just need to finalize the pause-play-autoplay workflow and we're good to go!
